# Generated by Django 3.2.9 on 2021-11-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency_code', models.CharField(max_length=10, null=True)),
                ('from_currency_name', models.CharField(max_length=10, null=True)),
                ('to_currency_code', models.CharField(max_length=10, null=True)),
                ('to_currency_name', models.CharField(max_length=10, null=True)),
                ('exchange_rate', models.FloatField(null=True)),
                ('last_refreshed', models.DateTimeField(null=True)),
                ('time_zone', models.CharField(max_length=10, null=True)),
                ('bid_price', models.FloatField(null=True)),
            ],
        ),
    ]
