# Generated by Django 3.2.9 on 2021-11-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='from_currency_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='to_currency_name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
